package com.adrienben.games.bagl.opengl.shader.compute;

import static org.lwjgl.opengl.GL42.*;
import static org.lwjgl.opengl.GL43.GL_SHADER_STORAGE_BARRIER_BIT;
import static org.lwjgl.opengl.GL44.GL_CLIENT_MAPPED_BUFFER_BARRIER_BIT;
import static org.lwjgl.opengl.GL44.GL_QUERY_BUFFER_BARRIER_BIT;

/**
 * Memory barrier types.
 *
 * @author adrien.
 */
public enum Barrier {

    VERTEX_ATTRIB_ARRAY(GL_VERTEX_ATTRIB_ARRAY_BARRIER_BIT),
    ELEMENT_ARRAY(GL_ELEMENT_ARRAY_BARRIER_BIT),
    UNIFORM(GL_UNIFORM_BARRIER_BIT),
    TEXTURE_FETCH(GL_TEXTURE_FETCH_BARRIER_BIT),
    SHADER_IMAGE_ACCESS(GL_SHADER_IMAGE_ACCESS_BARRIER_BIT),
    COMMAND(GL_COMMAND_BARRIER_BIT),
    PIXEL_BUFFER(GL_PIXEL_BUFFER_BARRIER_BIT),
    TEXTURE_UPDATE(GL_TEXTURE_UPDATE_BARRIER_BIT),
    BUFFER_UPDATE(GL_BUFFER_UPDATE_BARRIER_BIT),
    FRAMEBUFFER(GL_FRAMEBUFFER_BARRIER_BIT),
    TRANSFORM_FEEDBACK(GL_TRANSFORM_FEEDBACK_BARRIER_BIT),
    QUERY_BUFFER(GL_QUERY_BUFFER_BARRIER_BIT),
    ATOMIC_COUNTER(GL_ATOMIC_COUNTER_BARRIER_BIT),
    CLIENT_MAPPED_BUFFER(GL_CLIENT_MAPPED_BUFFER_BARRIER_BIT),
    SHADER_STORAGE(GL_SHADER_STORAGE_BARRIER_BIT);

    private final int glCode;

    Barrier(final int glCode) {
        this.glCode = glCode;
    }

    public int getGlCode() {
        return glCode;
    }
}
